version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  # memcached:
  #   image: memcached
  #   network_mode: host
  #   restart: always
  #   ports:
  #     - "11211:11211"
