name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag maxhollmann/podify:$(date +%s)
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master # https://github.com/marketplace/actions/publish-docker
      with:
        name: maxhollmann/podify
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
